#!/bin/bash

optionRegEx='^[1-5]$'

read -p "Insert a value between 1 to 5: (1, 5) " option

if [[ option =~ optionRegEx ]]; then
	case "$option" in
		"1") 
			read "Enter your name" name
			echo "Hi, $name"
			;;
		"2")
			read "Enter your lastname" lastname
			echo "Are you sure that $lastname is your lastname"
			;;
		"3")
			read "Enter your cellphone" cellphone
			echo "Alrigth, we're going to save this ($cellphone) into our database"
			;;
		"4")
			read "Enter your address" address
			echo "Alright, we're going to send the package to this address $address"
			;;
	esac
else
	echo "$option this is not valid option"
fi
